name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build step
        run: |
          echo "Starting build..."
          echo "Build completed successfully"

      - name: Test step
        run: |
          echo "Running  unit tests"
          echo "Running  end to end tests"
          echo "All tests passed"

      - name: Deploy step
        run: |
          echo "Deploying application"
          echo "Copying artifacts/dependencies to server"
          echo "Deployment completed successfully"
